language: haskell

os: linux
dist: bionic

addons:
  apt:
    update: true
    sources:
      - hvr-ghc
    packages: cabal-install-3.0

ghc:
  - 8.8.3

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y libasound2-dev libxpm-dev libmpd-dev
  - sudo apt-get install -y libxrandr-dev hspec-discover
  - export PATH=/opt/ghc/bin:$PATH

install:
  - cabal configure --enable-tests -fall_extensions
  - travis_wait 30 cabal build --only-dependecies --enable-tests
  - wget https://raw.github.com/ndmitchell/hlint/master/misc/travis.sh

script:
  - sh ./travis.sh src
  - cabal configure --enable-tests -fall_extensions && cabal build && cabal test
