# ghc 8.6.5
resolver: lts-14.20

packages:
 - .

flags:
 xmobar:
   all_extensions: true

extra-deps:
 - iwlib-0.1.0

nix:
    packages:
      - alsaLib
      - pkgconfig
      - wirelesstools
      - xorg.libX11
      - xorg.libXext
      - xorg.libXft
      - xorg.libXpm
      - xorg.libXrandr
      - xorg.libXScrnSaver
      - zlib
